export const FETCH_RESENDCODE_START = "FETCH_RESENDCODE_START";
export const FETCH_RESENDCODE_SUCCESS = "FETCH_RESENDCODE_SUCCESS";
export const FETCH_RESENDCODE_FAIL = "FETCH_RESENDCODE_FAIL";

export const FETCH_DETAIL_START = "FETCH_DETAIL_START";
export const FETCH_DETAIL_SUCCESS = "FETCH_DETAIL_SUCCESS"; 
export const FETCH_DETAIL_FAIL = "FETCH_DETAIL_FAIL";